export default {
    'Beaver City': 'Beaver County',
    Milford: 'Beaver County',
    Minersville: 'Beaver County',
    'Bear River': 'Box Elder County',
    'Brigham City': 'Box Elder County',
    Corinne: 'Box Elder County',
    Deweyville: 'Box Elder County',
    Elwood: 'Box Elder County',
    Fielding: 'Box Elder County',
    Garland: 'Box Elder County',
    Honeyville: 'Box Elder County',
    Howell: 'Box Elder County',
    Mantua: 'Box Elder County',
    Perry: 'Box Elder County',
    Plymouth: 'Box Elder County',
    Portage: 'Box Elder County',
    Snowville: 'Box Elder County',
    Tremonton: 'Box Elder County',
    Willard: 'Box Elder County',
    Amalga: 'Cache County',
    'Cache Valley Transit': 'Cache County',
    Clarkston: 'Cache County',
    Cornish: 'Cache County',
    'Hyde Park': 'Cache County',
    Hyrum: 'Cache County',
    Lewiston: 'Cache County',
    Logan: 'Cache County',
    Mendon: 'Cache County',
    Millville: 'Cache County',
    Newton: 'Cache County',
    Nibley: 'Cache County',
    Paradise: 'Cache County',
    Providence: 'Cache County',
    Richmond: 'Cache County',
    'River Heights': 'Cache County',
    Smithfield: 'Cache County',
    Trenton: 'Cache County',
    Wellsville: 'Cache County',
    'East Carbon': 'Carbon County',
    Helper: 'Carbon County',
    Price: 'Carbon County',
    Scofield: 'Carbon County',
    Wellington: 'Carbon County',
    'Dutch John': 'Daggett County',
    Manila: 'Daggett County',
    Bountiful: 'Davis County',
    Centerville: 'Davis County',
    Clearfield: 'Davis County',
    Clinton: 'Davis County',
    'Falcon Hill Clearfield': 'Davis County',
    'Falcon Hill Davis': 'Davis County',
    'Falcon Hill Sunset': 'Davis County',
    Farmington: 'Davis County',
    'Fruit Heights': 'Davis County',
    Kaysville: 'Davis County',
    Layton: 'Davis County',
    'South Weber': 'Davis County',
    Sunset: 'Davis County',
    Syracuse: 'Davis County',
    'West Bountiful': 'Davis County',
    'West Point': 'Davis County',
    'Woods Cross': 'Davis County',
    Altamont: 'Duchesne County',
    'Duchesne City': 'Duchesne County',
    Myton: 'Duchesne County',
    Roosevelt: 'Duchesne County',
    Tabiona: 'Duchesne County',
    'Castle Dale': 'Emery County',
    Clawson: 'Emery County',
    Cleveland: 'Emery County',
    Elmo: 'Emery County',
    'Emery City': 'Emery County',
    Ferron: 'Emery County',
    'Green River': 'Emery County',
    Huntington: 'Emery County',
    Orangeville: 'Emery County',
    Antimony: 'Garfield County',
    Boulder: 'Garfield County',
    'Bryce Canyon': 'Garfield County',
    Cannonville: 'Garfield County',
    Escalante: 'Garfield County',
    Hatch: 'Garfield County',
    Henrieville: 'Garfield County',
    Panguitch: 'Garfield County',
    Tropic: 'Garfield County',
    'Castle Valley': 'Grand County',
    Moab: 'Grand County',
    'Brian Head': 'Iron County',
    'Cedar City': 'Iron County',
    Enoch: 'Iron County',
    Kanarraville: 'Iron County',
    Paragonah: 'Iron County',
    Parowan: 'Iron County',
    Eureka: 'Juab County',
    Levan: 'Juab County',
    Mona: 'Juab County',
    Nephi: 'Juab County',
    'Rocky Ridge': 'Juab County',
    'Santaquin South': 'Juab County',
    Alton: 'Kane County',
    'Big Water': 'Kane County',
    Glendale: 'Kane County',
    Kanab: 'Kane County',
    Orderville: 'Kane County',
    Delta: 'Millard County',
    Fillmore: 'Millard County',
    Hinckley: 'Millard County',
    Holden: 'Millard County',
    Kanosh: 'Millard County',
    Leamington: 'Millard County',
    Lynndyl: 'Millard County',
    Meadow: 'Millard County',
    'Oak City': 'Millard County',
    Scipio: 'Millard County',
    'Morgan City': 'Morgan County',
    Circleville: 'Piute County',
    Junction: 'Piute County',
    Kingston: 'Piute County',
    Marysvale: 'Piute County',
    'Garden City': 'Rich County',
    Laketown: 'Rich County',
    Randolph: 'Rich County',
    Woodruff: 'Rich County',
    Alta: 'Salt Lake County',
    Bluffdale: 'Salt Lake County',
    Brighton: 'Salt Lake County',
    'Copperton Township': 'Salt Lake County',
    'Cottonwood Heights': 'Salt Lake County',
    Draper: 'Salt Lake County',
    'Emigration Canyon Township': 'Salt Lake County',
    Herriman: 'Salt Lake County',
    Holladay: 'Salt Lake County',
    'Inland Port Magna': 'Salt Lake County',
    'Inland Port Salt Lake City': 'Salt Lake County',
    'Inland Port Salt Lake Cnty': 'Salt Lake County',
    'Inland Port West Valley': 'Salt Lake County',
    'Kearns Township': 'Salt Lake County',
    'Magna Township': 'Salt Lake County',
    Midvale: 'Salt Lake County',
    Millcreek: 'Salt Lake County',
    Murray: 'Salt Lake County',
    Riverton: 'Salt Lake County',
    'Salt Lake City': 'Salt Lake County',
    Sandy: 'Salt Lake County',
    'SLC Convention Hotel': 'Salt Lake County',
    'South Jordan': 'Salt Lake County',
    Taylorsville: 'Salt Lake County',
    'Utah Data Center SL Co.': 'Salt Lake County',
    'West Jordan': 'Salt Lake County',
    'West Valley City': 'Salt Lake County',
    'White City Township': 'Salt Lake County',
    Blanding: 'San Juan County',
    Monticello: 'San Juan County',
    Centerfield: 'Sanpete County',
    Ephraim: 'Sanpete County',
    Fairview: 'Sanpete County',
    Fayette: 'Sanpete County',
    'Fountain Green': 'Sanpete County',
    Gunnison: 'Sanpete County',
    Manti: 'Sanpete County',
    Mayfield: 'Sanpete County',
    Moroni: 'Sanpete County',
    'Mt. Pleasant': 'Sanpete County',
    'Spring City': 'Sanpete County',
    Sterling: 'Sanpete County',
    Wales: 'Sanpete County',
    Annabella: 'Sevier County',
    Aurora: 'Sevier County',
    'Central Valley': 'Sevier County',
    Elsinore: 'Sevier County',
    Glenwood: 'Sevier County',
    Joseph: 'Sevier County',
    Koosharem: 'Sevier County',
    Monroe: 'Sevier County',
    Redmond: 'Sevier County',
    Richfield: 'Sevier County',
    Salina: 'Sevier County',
    Sigurd: 'Sevier County',
    Coalville: 'Summit County',
    Francis: 'Summit County',
    Henefer: 'Summit County',
    Kamas: 'Summit County',
    'Military Rec-Park City': 'Summit County',
    Oakley: 'Summit County',
    'Park City': 'Summit County',
    'Snyderville Basin Tr': 'Summit County',
    'Erda City': 'Tooele County',
    'Erda City West': 'Tooele County',
    Grantsville: 'Tooele County',
    'Lakepoint City': 'Tooele County',
    'Lakepoint Transit': 'Tooele County',
    Lincoln: 'Tooele County',
    'Rush Valley': 'Tooele County',
    'Stansbury Park': 'Tooele County',
    Stockton: 'Tooele County',
    'Tooele City': 'Tooele County',
    Vernon: 'Tooele County',
    Wendover: 'Tooele County',
    Ballard: 'Uintah County',
    Naples: 'Uintah County',
    Vernal: 'Uintah County',
    Alpine: 'Utah County',
    'American Fork': 'Utah County',
    'Bluffdale South': 'Utah County',
    'Cedar Fort': 'Utah County',
    'Cedar Hills': 'Utah County',
    'Eagle Mountain': 'Utah County',
    'Elk Ridge': 'Utah County',
    Fairfield: 'Utah County',
    Genola: 'Utah County',
    Goshen: 'Utah County',
    Highland: 'Utah County',
    Lehi: 'Utah County',
    Lindon: 'Utah County',
    Mapleton: 'Utah County',
    Orem: 'Utah County',
    Payson: 'Utah County',
    'Pleasant Grove': 'Utah County',
    Provo: 'Utah County',
    Salem: 'Utah County',
    Santaquin: 'Utah County',
    'Saratoga Springs': 'Utah County',
    'Spanish Fork': 'Utah County',
    Springville: 'Utah County',
    'UT Data Ctr UT Co': 'Utah County',
    Vineyard: 'Utah County',
    'Woodland Hills': 'Utah County',
    Charleston: 'Wasatch County',
    Daniel: 'Wasatch County',
    Heber: 'Wasatch County',
    Hideout: 'Wasatch County',
    Independence: 'Wasatch County',
    Interlaken: 'Wasatch County',
    Midway: 'Wasatch County',
    'Military Rec - GAEC PID': 'Wasatch County',
    'Military Rec - MWR Hotel': 'Wasatch County',
    'Military Rec-Hideout': 'Wasatch County',
    'Military Rec-Wasatch': 'Wasatch County',
    'Park City East': 'Wasatch County',
    Wallsburg: 'Wasatch County',
    'Apple Valley': 'Washington County',
    Enterprise: 'Washington County',
    Hildale: 'Washington County',
    Hurricane: 'Washington County',
    Ivins: 'Washington County',
    'La Verkin': 'Washington County',
    Leeds: 'Washington County',
    'New Harmony Town': 'Washington County',
    Rockville: 'Washington County',
    'Santa Clara': 'Washington County',
    Springdale: 'Washington County',
    'St. George': 'Washington County',
    Toquerville: 'Washington County',
    Virgin: 'Washington County',
    'Washington City': 'Washington County',
    Bicknell: 'Wayne County',
    Hanksville: 'Wayne County',
    Loa: 'Wayne County',
    Lyman: 'Wayne County',
    Torrey: 'Wayne County',
    'Falcon Hill Riverdale': 'Weber County',
    'Falcon Hill Roy': 'Weber County',
    'Farr West': 'Weber County',
    Harrisville: 'Weber County',
    Hooper: 'Weber County',
    Huntsville: 'Weber County',
    'Marriott-Slaterville': 'Weber County',
    Ogden: 'Weber County',
    'Plain City': 'Weber County',
    'Pleasant View': 'Weber County',
    Riverdale: 'Weber County',
    Roy: 'Weber County',
    Uintah: 'Weber County',
    'Washington Terrace': 'Weber County',
    'West Haven': 'Weber County',
}
